server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.zhang.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 41312019zhang

# Eureka 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 # 修改eureka上本服务的默认描述信息


# info配置 配置eureka页面上本服务的详细信息
info:
  app.name: zhang-springcloud
  company.name: blog.zhangstudy.com